### ISSUE TITLE
How can I get the file “book-DistMult-bce-decay.ckpt”

### ISSUE THREAD

**Issue by Tianchen627** [RichardHGL/UPGAN#2]
Traceback (most recent call last):
  File "main_pretrain.py", line 152, in <module>
    main()
  File "main_pretrain.py", line 140, in main
    trainer = Trainer_new(args=args, logger=logger)
  File "F:\UPGAN\UPGAN-master\pretrain\trainer.py", line 26, in __init__
    self.load_pretrain(args)
  File "F:\UPGAN\UPGAN-master\pretrain\base_trainer.py", line 301, in load_pretrain
    self.loadEmbedding(os.path.join(args.checkpoint_dir, filename), self.model, alternative='D_state_dict')
  File "F:\UPGAN\UPGAN-master\pretrain\base_trainer.py", line 308, in loadEmbedding
    assert os.path.isfile(filename), "Checkpoint file not found!"
AssertionError: Checkpoint file not found!

`--load_ckpt_file init/book-DistMult-bce-decay.ckpt` in run_book.sh

How can I get that file.thx!

**Comment by RichardHGL** [comment]
Actually, it's just a pretrained knowledge embedding (Many open source toolkit provide fast training of DIstMult. For example, use OpenKE toolkit (https://github.com/thunlp/OpenKE)). You can load entity embeddings and relation embeddings to speed up the training. 
It's also okay if we don't use such pretrained embeddings, but it may require more epoches to train model.
Another simple solution is that you can modify the pretrain folder to include the training of DistMult. (It's very fast under both 1-N or sample based training).

If you think it necessary, I can also upload this ckpt.

**Comment by Tianchen627** [comment]
Thanks for your reply.
Could you upload the ckpt for book/music/movie dataset respectively so that I can save time(tou lan) on running the code.
If it is inconvenient to upload,you have my E-mail zhangtianchen@gmail.com.
Thanks a lot!

BTW actually I don't understand the sentence "modify the pretrain folder to include the training of DistMult".In my perspective,I think I can modify the argument to load the embedding or modify the code to include the pre-training.

**Comment by RichardHGL** [comment]
I updated the readme page, you can find link to download DistMult files now!
